steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'CF'
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
      org: '82f90d5ftrial'
      space: 'dev'
